-- Start interactive EasyAlign in visual mode (e.g. vipge)
vim.keymap.set('x', "ge", "<Plug>(EasyAlign)", {noremap = false, desc = "Start interactive Easy Align"})
-- Start interactive EasyAlign for a motion/text object (e.g. geip)
vim.keymap.set('n', "ge", "<Plug>(EasyAlign)", {noremap = false, desc = "Start interactive Easy Align for a motion"})
vim.keymap.set('v', "ge", "<Plug>(EasyAlign)", {noremap = false, desc = "Start interative Easy Align for a motion"})
