-- Loading module of the config
require('config.which-key')
require('config.treesitter')
require('config.lualine')
require('config.indent-blankline')
require('config.nvim-tree')
require('config.ultisnips')
require('config.gitsigns')
require('config.cmp')
require('config.telescope')
require('config.comment')
require('config.vimcmdline')
require('config.autopairs')
require('config.easyalign')
require('config.vimtex')
require('config.texconceal')
require('config.nvimr')
require('config.vimwiki')

